# Name é o nome da nossa aplicação
name: Docker

on:
  # workflow_call significa que esse workflow será executado 
  # apenas quando chamado em outro workflow apenas
  workflow_call:

jobs:
  docker:    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    # Preparação do ambiente com docker build
    - name: Set up Docker Build
    - uses: docker/setup-buildx-action@v2.2.1

    # Para usar o container que vamos criar, será necessário colocá-lo em um repositório
    # Para isso precisamos fazer o login no DockerHub
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: vitordio
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
